### ISSUE TITLE
Running arrowjs on window 7

### ISSUE THREAD

**Issue by dhieugo** [TechMaster/ArrowCMS#11]
Hi,

I're trying to run arrowjs on window with nodejs but i got
```
C:\Users\user\Downloads\ArrowCMS-master\ArrowCMS-master\server.js:6
let Arrow = require('arrowjs');
^^^
SyntaxError: Unexpected strict mode reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

Do i need install iojs ?

**Comment by trquoccuong** [comment]
You need iojs version > 3.0.0 or nodejs version >= 4.0. For install ArrowCMS you need  nodejs, postgres, redis

**Comment by TechMaster** [comment]
We have not yet tested ArrowCMS on Windows. Please use Mac or Linux box to install Node.js and Arrowjs.io

**Comment by dhieugo** [comment]
Thank you, I will try to install arrowjs in Ubuntu :)
